### ISSUE TITLE
Chosing Specific Conda Environment When Launching LocalCluster

### ISSUE THREAD

**Issue by tdrobbin** [dask/dask-labextension#124] opened 2020-04-12 03:46 UTC
Hello, and thanks for an awesome extension! It makes working with/viewing status of clusters quite easy. I'm wondering if there's a way to specify a particular environment for the scheduler and workers when launching a local cluster. 

Currently when I launch a cluster it uses the same environment that jupyter lab itself was launched in. I'm not too knowledgeable when it comes to ipython kernel and conda enviroment interactions with jupyter, but when I have `nb_conda_kernels` installed in the environment running jupyter lab I can access all conda environments where I've installed `ipykernel`. I wonder if since the extension is running from within an environment with `nb_conda_kernels` installed, it might also be able to detect other available environments and optionally use them for launching the cluster - perhaps there could be a drop-down similar to what currently exists for selecting notebook kernels.

This isn't a major issue since I can obviously launch a cluster in my target environment from the console quite easily. But it would be nice to be able to use the helpful lab extension UI for the cluster management (scaling, visualizing tasks, etc...)

Thanks again!

**Comment by jsignell** [comment] 2020-04-15 21:08
That is an interesting idea @tdrobbin. I don't think there is currently a way to pass conda environments to `LocalCluster` objects, so I assume that would be where you'd need to start. I am a little wary of adding code to dask-labextension that relies on another labextension being installed. What you are proposing would make the most sense as a separate labextension. I think the audience is niche enough that it won't be implemented unless you implement it :)

**Comment by jsignell** [comment] 2020-04-17 18:17
On second thought I think this is a duplicate of #82. So maybe not so niche after all.

**Comment by jcrist** [comment] 2020-04-17 21:46
Yeah, this is a duplicate of #82. Closing.

**Closed by jcrist** 2020-04-17 21:46 UTC
