### ISSUE TITLE
Auto-detect Dashboard URL

### ISSUE THREAD

**Issue by msmicker** [dask/dask-labextension#126] opened 2020-04-18 21:25 UTC
Apologies if this is duplicated, but there are nuances to others reporting issues. My jupyterlab and cluster (SGE based) are remote and working splendidly. My network is open so no need for me to worry about port forwarding etc. I can reach the jupyterlab and dask dashboard directly from my workstation browser. The only thing not working is auto-detect. I just need to manually paste the URL that is showing either from the cluster UI or the client connection into the URL box and everything works.

It seems there must be a way for auto-detect to work since I am getting the URL address to paste directly from the extension itself.

**Comment by mrocklin** [comment] 2020-04-19 00:09
There is a little magnifying glass button next to the URL address bar.  Try
pressing that?

**Comment by msmicker** [comment] 2020-04-19 01:41
No such luck. I notice it makes the kernel indicator of my notebook blink but the url does not update. It says Dask and a uuid. I delete that and paste the url manually.

**Comment by mrocklin** [comment] 2020-04-19 02:01
Ok, then I'm not sure and you'll probably have to wait for one of the other
maintainers who knows more here

**Comment by ian-r-rose** [comment] 2020-04-19 02:28
@msmicker The extension tries to query the address of the dashboard by [executing](https://github.com/dask/dask-labextension/blob/master/src/index.ts#L506) code in the currently active kernel, but it is definitely not bullet proof.

The relevant code block is
```python
try:
    from dask.distributed import default_client as _internal_jlab_default_client
    display(_internal_jlab_default_client().cluster.dashboard_link)
except:
    pass
```
Can you try this manually in your kernel to see what the result is? We may be able to make the snippet more general/robust.

**Comment by msmicker** [comment] 2020-04-19 02:59
Thanks! This worked.

```python
try:
    from dask.distributed import default_client as _internal_jlab_default_client
    display(_internal_jlab_default_client().dashboard_link)
except:
    pass
```

**Comment by ian-r-rose** [comment] 2020-04-19 15:38
Thanks for checking @msmicker. Looks like @jacobtomlinson has already done some of the detective work here in https://github.com/dask/distributed/pull/3429. Sounds like we should update to use `Client.dashboard_link` instead of `Client.cluster.dashboard_link`, possibly with a fallback on the prior version for backward compatibility?

**Comment by jsignell** [comment] 2020-04-28 20:32
@msmicker are you interested in opening a PR for this? It seems that the solution that @ian-r-rose proposes is the right path.

**Comment by msmicker** [comment] 2020-05-06 03:47
I could try, but probably not in the next ~2-3 weeks? :)

**Comment by jacobtomlinson** [comment] 2020-05-20 14:05
I think something like this would work.

```python
try:
    from dask.distributed import default_client as _internal_jlab_default_client
    try:
        display(_internal_jlab_default_client().dashboard_link)
    except AttributeError:
        display(_internal_jlab_default_client().cluster.dashboard_link)
except:
    pass
```

**Comment by mrocklin** [comment] 2020-08-04 23:37
Fixed in https://github.com/dask/dask-labextension/pull/141

**Comment by mrocklin** [comment] 2020-08-05 00:10
OK, not actually fixed, or at least on in the use case that I'm playing with.

After having played with this a bit more I've found that the magnifying glass button works swell when I'm in the default IPython Kernel, but fails if I am using a different Python kernel.  Does this ring any bells @ian-r-rose ?

**Comment by mrocklin** [comment] 2020-08-05 00:12
To add more context, I'm using the `nb_conda_kernels` extension to JLab and installing `ipykernel` in my conda kernels so that they get picked up.

**Comment by ian-r-rose** [comment] 2020-08-05 00:24
Ooh, weird, not sure what that could be. Do you have a reproducible cobra
env that I can take for a spin?

**Comment by mrocklin** [comment] 2020-08-05 00:26
One sec. I'll try to produce a setup script.

**Comment by mrocklin** [comment] 2020-08-05 00:32
```
conda create -n auto-dashboard jupyterlab dask dask-labextension nb_conda_kernels nodejs -c conda-forge
conda activate auto-dashboard
jupyter labextension install dask-labextension
jupyter serverextension enable dask_labextension
conda create -n test dask ipykernel
jupyter lab
```
```python
from dask.distributed import Client
client = Client()
```

**Comment by ian-r-rose** [comment] 2020-08-05 01:13
Ah, I see what the issue is. We have a function to test whether we should check a given notebook for a dask client (so we don't, for instance, send code to a non-existent or non-python kernel): https://github.com/dask/dask-labextension/blob/a0c917f4415b49c880f396b5647a43993848f0e5/src/index.ts#L491-L498

That check is likely failing because the conda kernel has a different name than I had expected. I think the way forward is to actually check the language of the kernel, not just its name. Unfortunately, the language proper is only available asynchronously (probably this is why I initially checked the name). It's probably not a huge problem to make the kernel check async (though it's the type of thing that it would be good to have UI tests for! cf #139 )

**Closed** 2020-08-06 15:46 UTC
